name: Release Gobrick
# Invocable as a reusable workflow
# Can be manually triggered
on:
  workflow_dispatch:
  workflow_call:

jobs:
  csm-release:
    uses: dell/common-github-actions/.github/workflows/csm-release-libs.yaml@reusuable-release-workflow
    name: Release Libs
